apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-app-secrets
  namespace: ecommerce-app
type: Opaque
data:
  OIDC_PROVIDER_URL: aHR0cHM6Ly9tb2Rlc3QtY29yaS1yazRpYjZtZnpxLnByb2plY3RzLm9yeWFwaXMuY29t
  OIDC_CLIENT_ID: ZGU2YWFhMTgtYWFmYy00ZGRjLTg5ZDEtNzMwZGM5MDY1MDM5
  OIDC_CLIENT_SECRET: YUhvU1Y0dGdDSjlISEE3eE5VWEtwQ1ZiQ2U=
  OIDC_REDIRECT_URL: aHR0cDovL2xvY2FsaG9zdDo4MTgxL2FwaS9hdXRoL2NhbGxiYWNr
  AFRICASTALKING_USERNAME: c2FuZGJveA==
  AFRICASTALKING_API_KEY: YXRza185OGEyNDdlNTAyNTQ0MmFjMjU5NzU3ZGU1MGVlYWY1OWIzYjlhMTQ2YmIxMDcxZjdiZGU3NzQzNjM0ODcxYWI2ODQxNjRiNTM=
  AFRICASTALKING_RECIPIENT: KzI1NDcwNzY0OTMxMQ==
  AFRICASTALKING_SENDER_ID: QVRFQ09NWTIwMjU=
  SMTP_HOST: QVRFQ09NWTIwMjU=
  SMTP_PORT: NTg3
  SMTP_USERNAME: ZXJvdHVzaDc3QGdtYWlsLmNvbQ==
  SMTP_PASSWORD: eXJqZiBqanRkIHBkY2Mgc252Yg==
  ADMIN_EMAIL: aW5mb0BlcmljLW11dHVhLnNpdGU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce-app
  labels:
    app: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-app
          image: ecommerce-app:latest
          imagePullPolicy: Never # Use local image built by deploy.sh
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            # Add OIDC configuration (you'll need to set these)
            - name: OIDC_PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: OIDC_PROVIDER_URL
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: OIDC_CLIENT_ID
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: OIDC_REDIRECT_URL
            # Africa's Talking Environment Variables
            - name: AFRICASTALKING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: AFRICASTALKING_API_KEY
            - name: AFRICASTALKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: AFRICASTALKING_USERNAME
            - name: AFRICASTALKING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: AFRICASTALKING_SENDER_ID
            - name: AFRICASTALKING_RECIPIENT
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: AFRICASTALKING_RECIPIENT
            # SMTP Environment Variables
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: SMTP_PORT
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: SMTP_PASSWORD
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secrets
                  key: ADMIN_EMAIL
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL to start..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app
  namespace: ecommerce-app
  labels:
    app: ecommerce-app
spec:
  selector:
    app: ecommerce-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: NodePort
